Create error popover type
blackbaud/skyux-popovers pull request #158
Opened 2021-08-04 12:31 UTC by johnhwhite

2021-08-04 20:52 UTC, blackbaud-ado commented
Preview build at [https://developer.blackbaud.com/skyux-popovers?_sp.spa=pr-error-popover-option](https://developer.blackbaud.com/skyux-popovers?_sp.spa=pr-error-popover-option)

2021-08-05 01:56 UTC, blackbaud-ado commented
Preview build at [https://developer.blackbaud.com/skyux-popovers?_sp.spa=pr-error-popover-option](https://developer.blackbaud.com/skyux-popovers?_sp.spa=pr-error-popover-option)

2021-08-05 12:17 UTC, blackbaud-ado commented
Preview build at [https://developer.blackbaud.com/skyux-popovers?_sp.spa=pr-error-popover-option](https://developer.blackbaud.com/skyux-popovers?_sp.spa=pr-error-popover-option)

2021-08-05 18:53 UTC, Blackbaud-TrevorBurch requested changes
@johnhwhite - just a couple minor things

2021-08-05 18:53 UTC, Blackbaud-TrevorBurch commented on src/app/public/modules/popover/popover.component.ts
> +   * Specifies the type of popover.
Could we add the default here so that is shows up in the docs?

```
@default "info"
```

2021-08-05 18:53 UTC, Blackbaud-TrevorBurch commented on src/app/public/modules/popover/popover-content.component.ts
> +    if (config.popoverType) {
This is somewhat minor - but I would personally prefer that we test this. We do something similar here with placement on line 127 of the directive test (which is where all the popover tests live) where we give different values and make sure that the `ng-class` is working on the content.

Could we just add one test that tests that the class that we add is right for when it is `info`, `danger`, and when it is undefined?

2021-08-05 19:31 UTC, blackbaud-ado commented
Preview build at [https://developer.blackbaud.com/skyux-popovers?_sp.spa=pr-error-popover-option](https://developer.blackbaud.com/skyux-popovers?_sp.spa=pr-error-popover-option)

2021-08-06 14:36 UTC, Blackbaud-TrevorBurch requested changes
Two very nitpicky small things and then we are good :)

2021-08-06 14:36 UTC, Blackbaud-TrevorBurch commented on src/app/public/modules/popover/fixtures/popover.component.fixture.ts
> +  public popoverType: 'info' | 'danger' | undefined;
We shouldn't need the `| undefined` here.

2021-08-06 14:36 UTC, Blackbaud-TrevorBurch commented on src/app/public/modules/popover/popover.component.ts
> +   *
We don't need the extra line here. Typedoc will handle the annotations here to display them correctly.

2021-08-06 14:39 UTC, Blackbaud-TrevorBurch commented on src/app/public/modules/popover/popover-content.component.ts
> +    /* istanbul ignore else */
We should be able to remove this ignore now that we have a test for this - correct?

2021-08-06 16:30 UTC, blackbaud-ado commented
Preview build at [https://developer.blackbaud.com/skyux-popovers?_sp.spa=pr-error-popover-option](https://developer.blackbaud.com/skyux-popovers?_sp.spa=pr-error-popover-option)

2021-08-06 17:50 UTC, Blackbaud-TrevorBurch approved these changes

2021-08-06 17:51 UTC, merged